spring:
  application:
    name: davivienda
  jackson:
    default-property-inclusion: non_null
    property-naming-strategy: LOWER_CAMEL_CASE
server:
  port: 8080
  servlet:
    context-path: /davivienda

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
  show-actuator: true
  show-login-endpoint: true


